import { levels } from './assets/levels.mjs';
import { screenToScene, hitTest, thumbnailTransform, canvasBackingSize, targetCanvasBackingSize, markerBounds, isValidTap, moveSearchCursor } from './assets/geometry.mjs';
import { fitCamera, resizeCamera, clampTransform, zoomAroundPoint, sceneScaleLimits, districtSwipeDirection } from './assets/viewport.mjs';
import { cameraForDistrict, createDistrictState, districtAnnouncement, selectDistrict, stepDistrict } from './assets/district-state.mjs';
import { districtForTarget as targetDistrict } from './assets/district-catalogue.mjs';
import { createCampaign, freshLevel, findCampaignTarget, loadProgress, saveProgress } from './assets/campaign.mjs';
import { createContinuousRun, restartContinuousRun, findContinuousTarget, advanceContinuousRound, loadContinuousProgress, saveContinuousProgress } from './assets/continuous.mjs';
import { applyCampaignClue, applyContinuousClue } from './assets/assistance.mjs';
import { loadSettings, saveSettings, updateSetting } from './assets/settings.mjs';
import { createMenuState, closeMenu, menuHostTransition } from './assets/menu-state.mjs';
import { formatElapsed, resolveGameContext, hydrateDistrictProgress, snapshotDistrictProgress, focusDistrictTarget, migrationNotice, targetPreview } from './assets/game-state.mjs';
import { createCompletionPresenter, createEffects, createEffectsLifecycle, createFeedbackCleanup, particleFeedbackMode, reconfigureEffects } from './assets/effects.mjs';

const $ = (selector) => document.querySelector(selector);
const viewport = $('#viewport'), scene = $('#scene'), sceneImage = $('#scene-image'), sceneIncoming = $('#scene-image-next'), markers = $('#markers'), panel = $('#panel'), body = $('#panel-body');
const constrainedTargetMedia = window.matchMedia?.('(orientation: landscape) and (max-height: 520px)');
const reducedMotionMedia = window.matchMedia?.('(prefers-reduced-motion: reduce)');
let storage; try { storage = window.localStorage; } catch { storage = null; }
const restored = loadProgress(storage, levels), endlessRestored = loadContinuousProgress(storage, levels);
let campaign = restored.state, endless = endlessRestored.state, mode = readMode();
let settings = loadSettings(storage).state;
let effects = createEffects({ sound: settings.sound, motion: settings.motion, prefersReducedMotion: reducedMotionMedia?.matches });
const feedbackCleanup = createFeedbackCleanup(), lastFoundOwner = {};
let menuState = createMenuState(), menuOpener = null, menuView = null;
const restoreWarnings = {journey: restored.warning, continuous: endlessRestored.warning};
const gameContext = () => resolveGameContext(levels, {mode, campaign, continuous: endless});
let level = gameContext().level;
let districtState = hydrateDistrictProgress(gameContext().progress, level).districtState;
let camera = { x: 0, y: 0, scale: 1 }, size = { width: 1, height: 1 };
let ready = false, loadedImage = null, loadedImageDistrictId = null, selected = null, lastFoundId = null, loadToken = 0, toastTimer, hintTimer, noteTimer, saveTimer, transitionTimer, tap = null, pinch = null, lastTick = performance.now(), storageNotice = false;
const pointers = new Map();
let cursor = { x: 0, y: 0 };

const words = {
  en: { brand: 'GUJARAT', endlessBrand: 'ENDLESS', find: 'Find in the crowd', left: 'left', hint: 'Hint', levels: 'Game menu', menu: 'Game menu', play: 'Play', profile: 'Profile', settings: 'Settings', howTo: 'How to play', guest: 'Guest player', cloudUnavailable: 'Cloud profile unavailable', sound: 'Sound', unlimited: 'Unlimited clues', systemMotion: 'System motion', reducedMotion: 'Reduced motion', contrast: 'High contrast', standardContrast: 'Standard contrast', resetCoach: 'Show coach again', resetProgress: 'Reset device progress', resetProgressTitle: 'Reset all device progress?', resetProgressCopy: 'Journey, Continuous, and camera progress will be cleared on this device.', reset: 'Reset progress', pause: 'Take a breather', continue: 'Continue exploring', language: 'ગુજરાતીમાં રમો', restart: 'Restart this level', restartTitle: 'Start this level again?', restartCopy: 'Your finds and hints in this level will reset. Other completed levels stay saved.', cancel: 'Keep exploring', time: 'Active time', hints: 'Hints used', complete: 'Scene complete', allComplete: 'You found Gujarat!', next: 'Next level', replay: 'Play this level again', list: 'Modes & levels', found: 'Found', loading: 'Opening the scene…', error: 'This district could not load. Check your connection and try again.', retry: 'Try again', gesture: 'Drag to explore · swipe at fit view to change district', inspect: 'Match the little details. You can find these in any order.', foundCopy: 'You have already found this one.', clue: 'Give me a clue', region: 'Show a search area', used: 'Both clues revealed', noHints: 'No hints left in this round', back: 'Back to the scene', locked: 'Complete the previous level', saved: 'Progress saves on this device.', unsaved: 'Progress cannot be saved on this device.', updated: 'This scene was updated, so its old finds have been reset.', help: 'Drag to explore; pinch or use + / − to zoom. At fit view, swipe horizontally to change district. Keyboard: arrows aim, Shift + arrows pan, Enter searches at the cursor, Home shows the whole district.', close: 'Close', zoomIn: 'Zoom in', zoomOut: 'Zoom out', overview: 'See the whole district', maxZoom: 'MAX', miss: 'Keep looking — match the details in the target.', journey: 'Level Journey', journeyCopy: 'Handcrafted Gujarat chapters. Finish one to open the next.', continuous: 'Continuous Hunt', continuousCopy: 'Seeded rounds that grow harder and keep your score.', round: 'Round', score: 'Score', roundComplete: 'Round complete', nextRound: 'Next round', newRun: 'Start a new run', newRunTitle: 'Replace this continuous run?', newRunCopy: 'Your continuous score and round will reset. Level Journey progress stays safe.', startNew: 'Yes, start fresh', points: 'Round points', previousDistrict: 'Previous district', nextDistrict: 'Next district', chooseDistrict: 'Choose district', goToDistrict: 'Go to district' },
  gu: { brand: 'ગુજરાત', endlessBrand: 'અનંત શોધ', find: 'ભીડમાં શોધો', left: 'બાકી', hint: 'ઈશારો', levels: 'ગેમ મેનુ', menu: 'ગેમ મેનુ', play: 'રમો', profile: 'પ્રોફાઇલ', settings: 'સેટિંગ્સ', howTo: 'કેવી રીતે રમવું', guest: 'મહેમાન ખેલાડી', cloudUnavailable: 'ક્લાઉડ પ્રોફાઇલ ઉપલબ્ધ નથી', sound: 'અવાજ', unlimited: 'અમર્યાદિત ઈશારા', systemMotion: 'સિસ્ટમ ગતિ', reducedMotion: 'ઓછી ગતિ', contrast: 'વધુ કોન્ટ્રાસ્ટ', standardContrast: 'સામાન્ય કોન્ટ્રાસ્ટ', resetCoach: 'કોચ ફરી બતાવો', resetProgress: 'ઉપકરણની પ્રગતિ ભૂંસો', resetProgressTitle: 'ઉપકરણની બધી પ્રગતિ ભૂંસવી?', resetProgressCopy: 'આ ઉપકરણ પર સફર, અનંત શોધ અને કેમેરા પ્રગતિ ભૂંસાશે.', reset: 'પ્રગતિ ભૂંસો', pause: 'થોડો વિરામ', continue: 'શોધવાનું ચાલુ રાખો', language: 'Play in English', restart: 'આ સ્તર ફરી શરૂ કરો', restartTitle: 'આ સ્તર ફરી શરૂ કરવું છે?', restartCopy: 'આ સ્તરની શોધ અને ઈશારા ફરી શરૂ થશે. બીજા પૂર્ણ સ્તરો સાચવેલા રહેશે.', cancel: 'શોધવાનું ચાલુ રાખો', time: 'રમતનો સમય', hints: 'વપરાયેલા ઈશારા', complete: 'બધું મળી ગયું', allComplete: 'ગુજરાતની શોધ પૂરી!', next: 'આગળનું સ્તર', replay: 'આ સ્તર ફરી રમો', list: 'રમત અને સ્તરો', found: 'મળ્યું', loading: 'વિસ્તાર ખૂલી રહ્યો છે…', error: 'વિસ્તાર ખૂલી શક્યો નહીં. કનેક્શન તપાસીને ફરી પ્રયત્ન કરો.', retry: 'ફરી પ્રયત્ન કરો', gesture: 'ખસેડો · આખું દૃશ્ય હોય ત્યારે વિસ્તાર બદલવા સ્વાઇપ કરો', inspect: 'નાની વિગતો સરખાવો. કોઈપણ ક્રમમાં શોધી શકો છો.', foundCopy: 'આ વસ્તુ તમે શોધી લીધી છે.', clue: 'એક ઈશારો આપો', region: 'શોધવાનો વિસ્તાર બતાવો', used: 'બંને ઈશારા બતાવ્યા', noHints: 'આ રાઉન્ડમાં ઈશારા બાકી નથી', back: 'દૃશ્ય પર પાછા જાઓ', locked: 'પહેલાનું સ્તર પૂરું કરો', saved: 'આ ઉપકરણ પર પ્રગતિ સચવાય છે.', unsaved: 'આ ઉપકરણ પર પ્રગતિ સાચવી શકાતી નથી.', updated: 'દૃશ્ય બદલાયું છે, તેથી તેની જૂની શોધ ફરી શરૂ થશે.', help: 'ખસેડો; ઝૂમ માટે બે આંગળી અથવા + / − વાપરો. આખો વિસ્તાર દેખાય ત્યારે વિસ્તાર બદલવા આડો સ્વાઇપ કરો. કીબોર્ડ: તીરથી નિશાન ખસેડો, Shift + તીરથી દૃશ્ય ખસેડો, Enterથી શોધો, Homeથી આખો વિસ્તાર જુઓ.', close: 'બંધ કરો', zoomIn: 'મોટું કરો', zoomOut: 'નાનું કરો', overview: 'આખો વિસ્તાર જુઓ', maxZoom: 'મહત્તમ', miss: 'શોધતા રહો — લક્ષ્યની વિગતો સરખાવો.', journey: 'સ્તરની સફર', journeyCopy: 'ગુજરાતના રચેલા પ્રકરણો. એક પૂરું કરો, પછીનું ખૂલે.', continuous: 'અનંત શોધ', continuousCopy: 'દરેક રાઉન્ડ વધુ કઠિન, તમારો સ્કોર સતત આગળ.', round: 'રાઉન્ડ', score: 'સ્કોર', roundComplete: 'રાઉન્ડ પૂર્ણ', nextRound: 'આગળનો રાઉન્ડ', newRun: 'નવી રમત શરૂ કરો', newRunTitle: 'આ અનંત રમત બદલવી છે?', newRunCopy: 'સ્કોર અને રાઉન્ડ ફરી શરૂ થશે. સ્તરની સફર સુરક્ષિત રહેશે.', startNew: 'હા, નવી શરૂઆત', points: 'રાઉન્ડના પોઈન્ટ', previousDistrict: 'પાછલો વિસ્તાર', nextDistrict: 'આગળનો વિસ્તાર', chooseDistrict: 'વિસ્તાર પસંદ કરો', goToDistrict: 'વિસ્તારમાં જાઓ' },
};

const text = () => words[campaign.locale];
const name = (item) => item.name[campaign.locale];
const progress = () => gameContext().progress;
const activeDistrict = () => gameContext().district;
const levelTargets = () => gameContext().allTargets;
const activeTargets = () => gameContext().targets;
function setProgress(next) { if (mode === 'continuous') endless = next; else campaign.levels[level.id] = next; }
function restoreDistrictState(options = {}) { setProgress(hydrateDistrictProgress(progress(), level, options)); districtState = progress().districtState; }
function progressCopy() { const blocked = mode === 'journey' ? campaign.migrationBlocked : endless.migrationBlocked; return blocked ? migrationNotice(blocked, campaign.locale) : storageNotice ? text().unsaved : text().saved; }
function renderMigrationNotice() { const node = $('#migration-notice'); node.textContent = migrationNotice((mode === 'journey' ? campaign.migrationBlocked : endless.migrationBlocked) || restoreWarnings[mode], campaign.locale); node.hidden = !node.textContent; }
const sceneTargets = () => activeTargets().filter((target) => target.districtId === activeDistrict().id);
const districtForTarget = (target) => targetDistrict(level, target?.id);
const hintBudget = () => progress().hintsRemaining + Object.values(progress().hintStages).reduce((sum, stage) => sum + stage, 0);
const activeMenuSection = () => Object.entries(menuState.sections).find(([, active]) => active)?.[0] || 'play';
const completionPresenter = createCompletionPresenter({ isComplete: () => ready && progress().complete, isPanelOpen: () => panel.open, present: showComplete });
const effectsLifecycle = createEffectsLifecycle({ save, dispose: () => effects.dispose(), rebuild: rebuildEffects });
function readMode() { try { return storage?.getItem('hidden-gujarat-mode-v1') === 'continuous' ? 'continuous' : 'journey'; } catch { return 'journey'; } }
function el(tag, className, value) { const node = document.createElement(tag); if (className) node.className = className; if (value !== undefined) node.textContent = value; return node; }
function button(label, action, kind = 'secondary') { const node = el('button', kind, label); node.type = 'button'; node.addEventListener('click', action); return node; }
function toast(message) { clearTimeout(toastTimer); $('#toast').textContent = message; $('#toast').classList.add('show'); toastTimer = setTimeout(() => $('#toast').classList.remove('show'), 3000); }
function renderCursor() { const node = $('.keyboard-cursor'); node.style.left = cursor.x + 'px'; node.style.top = cursor.y + 'px'; }
function tick() { const now = performance.now(); if (ready && !panel.open && !document.hidden && !progress().complete) progress().elapsedMs += Math.max(0, now - lastTick); lastTick = now; }
function rememberCamera() { if (!ready) return; setProgress(snapshotDistrictProgress(progress(), districtState, camera)); districtState = progress().districtState; }
function save() { tick(); rememberCamera(); const a = saveProgress(storage, campaign), b = saveContinuousProgress(storage, endless); try { storage?.setItem('hidden-gujarat-mode-v1', mode); } catch {} if ((a.warning === 'storage' || b.warning === 'storage') && !storageNotice) { storageNotice = true; toast(text().unsaved); } }
function scheduleSave() { clearTimeout(saveTimer); saveTimer = setTimeout(save, 350); }
function rect() { return { width: viewport.clientWidth, height: viewport.clientHeight }; }
function scales() { return sceneScaleLimits(size, activeDistrict(), window.devicePixelRatio || 1); }
function setBox(node, bounds) { Object.assign(node.style, { left: bounds.x + 'px', top: bounds.y + 'px', width: bounds.width + 'px', height: bounds.height + 'px' }); }
function renderCamera() { const limits = scales(), atMax = camera.scale >= limits.max - 1e-9, label = Math.round(camera.scale / limits.min * 100) + '%'; scene.style.transform = `translate3d(${camera.x}px,${camera.y}px,0) scale(${camera.scale})`; scene.style.setProperty('--zoom', camera.scale); $('#zoom-label').textContent = atMax ? label + ' · ' + text().maxZoom : label; $('#zoom-in').disabled = atMax; for (const marker of markers.children) { const target = activeDistrict().targets.find((item) => item.id === marker.dataset.id); if (target) setBox(marker, markerBounds(target.visualBounds, camera.scale)); } }
function zoom(factor, point = { x: size.width / 2, y: size.height / 2 }) { if (!ready) return; const district = activeDistrict(), limits = scales(); camera = clampTransform(zoomAroundPoint(camera, Math.min(limits.max, Math.max(limits.min, camera.scale * factor)), point), size, district); renderCamera(); scheduleSave(); }
function overview() { if (!ready) return; camera = fitCamera(size, activeDistrict(), 'overview', window.devicePixelRatio || 1); renderCamera(); scheduleSave(); }
function thumb(target, cssSize) { const preview = targetPreview(target, level, loadedImage && loadedImageDistrictId === activeDistrict().id ? loadedImageDistrictId : null, campaign.locale); if (!preview.available) return el('span', 'target-preview-unavailable', preview.message); const canvas = el('canvas'), ratio = window.devicePixelRatio || 1, frame = cssSize === undefined ? targetCanvasBackingSize(constrainedTargetMedia?.matches === true, ratio) : canvasBackingSize(cssSize, ratio), inset = 8 * frame.ratio; canvas.width = frame.pixels; canvas.height = frame.pixels; canvas.setAttribute('aria-hidden', 'true'); const ctx = canvas.getContext('2d'); ctx.fillStyle = '#eee0bb'; ctx.fillRect(0, 0, frame.pixels, frame.pixels); const crop = preview.crop, fit = thumbnailTransform(crop, { width: frame.pixels - inset, height: frame.pixels - inset }); ctx.drawImage(loadedImage, crop.x, crop.y, crop.width, crop.height, (frame.pixels - crop.width * fit.scale) / 2, (frame.pixels - crop.height * fit.scale) / 2, crop.width * fit.scale, crop.height * fit.scale); return canvas; }

function applyTheme() { document.documentElement.dataset.contrast = settings.contrast; document.documentElement.dataset.motion = settings.motion; }
function rebuildEffects() { effects = reconfigureEffects(effects, { sound: settings.sound, motion: settings.motion, prefersReducedMotion: reducedMotionMedia?.matches }); }
function restartFeedback(node, className, duration = 560) { if (!node) return; node.classList.remove(className); void node.offsetWidth; node.classList.add(className); feedbackCleanup.replace(node, className, () => node.classList.remove(className), duration); }
function particleBurst(point, motion) { const layer = $('#feedback-layer'); if (!layer) return; const mode = particleFeedbackMode(motion), offsets = [[0, -34], [29, -17], [31, 15], [0, 33], [-29, 15], [-29, -17]]; layer.replaceChildren(); for (const [x, y] of offsets) { const particle = el('i', 'feedback-particle feedback-particle--' + mode); particle.style.left = point.x + 'px'; particle.style.top = point.y + 'px'; particle.style.setProperty('--burst-x', x + 'px'); particle.style.setProperty('--burst-y', y + 'px'); layer.append(particle); } feedbackCleanup.replace(layer, 'particles', () => layer.replaceChildren(), 560); }
function markLastFound(targetId) { lastFoundId = targetId; feedbackCleanup.replace(lastFoundOwner, 'last-found', () => { lastFoundId = null; }, 560); }
function playFindFeedback(point, targetId) { const motion = effects.playFind(); markLastFound(targetId); restartFeedback($('#count'), 'count-roll'); if (mode === 'continuous') restartFeedback($('#score'), 'score-tick'); particleBurst(point, motion); }
function playMissFeedback() { effects.playMiss(); restartFeedback(viewport, 'miss-pulse', 380); }
function playCompleteFeedback(point, targetId) { const motion = effects.playComplete(); markLastFound(targetId); restartFeedback($('#count'), 'count-roll'); if (mode === 'continuous') restartFeedback($('#score'), 'score-tick'); particleBurst(point, motion); }
function renderDistrictNavigation(announce = false) { const t = text(), district = activeDistrict(), buttons = [...document.querySelectorAll('.district-button')]; $('#district-navigation').setAttribute('aria-label', t.chooseDistrict); $('#previous-district').setAttribute('aria-label', t.previousDistrict); $('#next-district').setAttribute('aria-label', t.nextDistrict); $('#district-name').textContent = name(district); for (const [index, node] of buttons.entries()) { const item = level.districts[index], active = item?.id === district.id; node.hidden = !item; if (!item) continue; node.dataset.districtId = item.id; node.setAttribute('aria-label', `${t.goToDistrict}: ${name(item)}`); node.setAttribute('aria-pressed', String(active)); node.title = name(item); } if (announce) $('#district-announcement').textContent = districtAnnouncement(districtState, level); }
function updateCopy() { const t = text(); renderMigrationNotice(); document.documentElement.lang = campaign.locale; applyTheme(); $('#chapter-label').textContent = mode === 'continuous' ? `${t.endlessBrand} / ${t.round} ${String(endless.round).padStart(2, '0')}` : `${t.brand} / ${String(levels.indexOf(level) + 1).padStart(2, '0')}`; $('#level-name').textContent = name(level); $('#search-label').textContent = t.find; $('#gesture-note').textContent = t.gesture; $('#loading-copy').textContent = t.loading; $('#retry').textContent = t.retry; $('#target-list').setAttribute('aria-label', campaign.locale === 'gu' ? 'શોધવાની વસ્તુઓ' : 'Objects to find'); if (ready) sceneImage.alt = `${name(level)} — ${name(activeDistrict())}`; for (const [id, label] of [['levels-button', t.levels], ['pause-button', t.pause], ['close-panel', t.close], ['zoom-in', t.zoomIn], ['zoom-out', t.zoomOut], ['overview', t.overview]]) $('#' + id).setAttribute('aria-label', label); viewport.setAttribute('aria-label', t.help); renderDistrictNavigation(); }
function renderTargets() { const list = $('#target-list'), scrollX = list.scrollLeft, scrollY = list.scrollTop; list.replaceChildren(); markers.replaceChildren(); for (const target of activeTargets()) { const found = progress().foundIds.includes(target.id), stage = progress().hintStages[target.id] || 0, district = districtForTarget(target), card = button('', () => showTarget(target), 'target-card' + (found ? ' found' : '') + (target.id === lastFoundId ? ' card-complete' : '') + (selected === target.id ? ' selected' : '')); card.dataset.id = target.id; card.setAttribute('aria-label', `${name(target)} — ${name(district)}${found ? ' — ' + text().found : ''}`); card.setAttribute('aria-pressed', String(selected === target.id)); card.append(thumb(target), el('span', 'name', name(target)), el('span', 'district-badge', name(district)), el('span', 'clue-stage', stage === 2 ? '2 / 2' : stage === 1 ? '1 / 2' : '2 clues')); list.append(card); if (found && target.districtId === activeDistrict().id) { const marker = el('div', 'marker' + (target.id === lastFoundId ? ' find-outline' : '')); marker.dataset.id = target.id; markers.append(marker); } } list.scrollLeft = scrollX; list.scrollTop = scrollY; updateCounts(); renderCamera(); }
function updateCounts() { const p = progress(), t = text(), total = activeTargets().length; $('#count').textContent = p.foundIds.length + ' / ' + total; $('#count').setAttribute('aria-label', t.found + ' ' + p.foundIds.length + ' / ' + total); $('#score').hidden = mode !== 'continuous'; $('#score').textContent = t.score + ' ' + endless.score.toLocaleString(); $('#remaining-label').textContent = (total - p.foundIds.length) + ' ' + t.left; $('#hint-button').replaceChildren(document.createTextNode(t.hint + ' '), el('span', '', settings.unlimitedClues ? '∞' : p.hintsRemaining)); $('#hint-button').disabled = !ready || p.complete; }
function openPanel(title, preserveMenu = false, menuClass = preserveMenu) { tick(); $('#panel-title').textContent = title; panel.classList.toggle('menu-panel', menuClass); if (!preserveMenu) { body.replaceChildren(); menuView = null; } if (!panel.open) panel.showModal(); }
function closePanel() { if (!panel.open) { menuState = closeMenu(menuState); menuOpener = null; return; } panel.close(); }
function showTarget(target) { if (!ready) return; selected = target.id; const t = text(), p = progress(), found = p.foundIds.includes(target.id), stage = p.hintStages[target.id] || 0, district = districtForTarget(target), elsewhere = target.districtId !== activeDistrict().id; for (const card of $('#target-list').children) { card.classList.toggle('selected', card.dataset.id === selected); card.setAttribute('aria-pressed', String(card.dataset.id === selected)); } openPanel(name(target)); const art = el('div', 'detail-art'); art.append(thumb(target, 154)); body.append(el('p', 'target-district-label', name(district)), art, el('p', 'detail-description', found ? t.foundCopy : t.inspect)); if (elsewhere) body.append(button(`${t.goToDistrict}: ${name(district)}`, () => switchDistrict(target.districtId), 'primary go-to-district')); if (stage > 0) body.append(el('div', 'clue', target.clues[campaign.locale][0])); if (stage === 2) body.append(el('p', 'small-copy', target.clues[campaign.locale][1])); if (!found) { const available = settings.unlimitedClues || p.hintsRemaining > 0; const hint = button(stage >= 2 ? t.used : !available ? t.noHints : (stage === 0 ? t.clue : t.region) + (settings.unlimitedClues ? '' : ' · ' + p.hintsRemaining), () => useHint(target), 'primary'); hint.disabled = stage >= 2 || !available; body.append(hint); } body.append(button(t.back, closePanel)); }
function focusHintRegion(target) { setProgress(focusDistrictTarget(progress(), level, target.id, {viewport: size, pixelRatio: window.devicePixelRatio || 1, hint: true})); districtState = progress().districtState; camera = cameraForDistrict(districtState, target.districtId); setBox($('#hint-region'), target.hintRegion); $('#hint-region').hidden = false; renderCamera(); clearTimeout(hintTimer); hintTimer = setTimeout(() => { $('#hint-region').hidden = true; }, 9000); toast(target.clues[campaign.locale][1]); renderTargets(); save(); }
function useHint(target) { const result = mode === 'continuous' ? applyContinuousClue(endless, levels, target.id, settings) : applyCampaignClue(campaign, levels, level.id, target.id, settings); if (mode === 'continuous') endless = result.state; else campaign = result.state; if (!result.spent) return; updateCounts(); save(); if (result.stage === 1) { showTarget(target); return; } closePanel(); if (target.districtId !== activeDistrict().id) { switchDistrict(target.districtId, undefined, target.id); return; } focusHintRegion(target); }

function modeSwitch() { const t = text(), wrap = el('div', 'mode-switch'); for (const [value, title, copy] of [['journey', t.journey, t.journeyCopy], ['continuous', t.continuous, t.continuousCopy]]) { const choice = button('', () => switchMode(value), 'mode-choice' + (mode === value ? ' active' : '')); choice.setAttribute('aria-pressed', String(mode === value)); choice.append(el('strong', '', title), el('span', '', copy)); wrap.append(choice); } return wrap; }
function switchMode(nextMode) { if (nextMode === mode) return; save(); if (panel.open) closePanel(); ready = false; mode = nextMode; level = gameContext().level; loadLevel(level.id); }
function createMenuView() { const nav = el('nav', 'menu-navigation'); nav.setAttribute('aria-label', text().menu); const sections = new Map(); for (const [section, label] of [['play', text().play], ['profile', text().profile], ['settings', text().settings], ['help', text().howTo]]) { const item = button(label, () => renderMenu(section), 'menu-tab'); item.dataset.section = section; item.setAttribute('aria-controls', 'menu-' + section); nav.append(item); const content = el('section', 'menu-section'); content.id = 'menu-' + section; content.setAttribute('aria-labelledby', 'menu-' + section + '-title'); sections.set(section, content); } return {nav, sections}; }
function renderMenu(section = 'play', opener = menuOpener) { const transition = menuHostTransition(menuState, section, Boolean(menuView && body.contains(menuView.nav))); menuState = transition.state; menuOpener = opener || menuOpener || $('#levels-button'); openPanel(text().menu, transition.preserveBody, transition.menuClass); if (!menuView || !body.contains(menuView.nav)) { menuView = createMenuView(); body.append(menuView.nav, ...menuView.sections.values()); } const active = transition.section; for (const item of menuView.nav.children) { const isActive = item.dataset.section === active; item.classList.toggle('active', isActive); item.setAttribute('aria-current', isActive ? 'page' : 'false'); } for (const [name, content] of menuView.sections) content.hidden = name !== active; const content = menuView.sections.get(active); content.replaceChildren(); if (active === 'play') renderPlayMenu(content); else if (active === 'profile') renderProfileMenu(content); else if (active === 'settings') renderSettingsMenu(content); else renderHelpMenu(content); }
function renderPlayMenu(content) { const title = el('h3', '', text().play); title.id = 'menu-play-title'; content.append(title, modeSwitch()); if (mode === 'continuous') { const summary = el('div', 'run-summary'); summary.append(el('span', '', text().round + ' ' + endless.round), el('strong', '', endless.score.toLocaleString()), el('small', '', text().score)); content.append(summary, button(text().continue, closePanel, 'primary'), button(text().newRun, showNewRun, 'secondary danger')); return; } const grid = el('div', 'level-grid'); levels.forEach((item, index) => { const p = campaign.levels[item.id], unlocked = campaign.unlockedLevelIds.includes(item.id), tile = button('', () => { if (!unlocked) return; closePanel(); loadLevel(item.id); }, 'level-tile' + (item.id === level.id ? ' current' : '')); tile.disabled = !unlocked; const image = el('img'); image.src = item.districts[0].preview; image.alt = ''; image.loading = 'lazy'; const copy = el('div', 'tile-copy'); copy.append(el('small', '', String(index + 1).padStart(2, '0') + ' / ' + item.difficulty[campaign.locale]), el('b', '', name(item)), el('small', '', unlocked ? p.foundIds.length + ' / ' + item.targets.length + ' ' + text().found : text().locked)); const bar = el('progress'); bar.max = item.targets.length; bar.value = p.foundIds.length; bar.setAttribute('aria-label', name(item)); copy.append(bar); tile.append(image, copy); grid.append(tile); }); content.append(grid); }
function renderProfileMenu(content) { const title = el('h3', '', text().profile); title.id = 'menu-profile-title'; const card = el('div', 'profile-card'); const identity = el('div', 'profile-identity'); identity.append(el('strong', '', text().guest), el('p', '', text().cloudUnavailable)); card.append(el('div', 'profile-avatar', 'G'), identity); content.append(title, card, el('p', 'small-copy', progressCopy())); }
function settingRow(label, control) { const row = el('label', 'setting-row'); row.append(el('span', '', label), control); return row; }
function settingToggle(key, label) { const input = document.createElement('input'); input.type = 'checkbox'; input.checked = settings[key] === true; input.addEventListener('change', () => { settings = updateSetting(settings, key, input.checked); saveSettings(storage, settings); applyTheme(); if (key === 'sound') rebuildEffects(); }); return settingRow(label, input); }
function renderSettingsMenu(content) { const title = el('h3', '', text().settings); title.id = 'menu-settings-title'; const form = el('form', 'settings-form'); form.addEventListener('submit', (event) => event.preventDefault()); form.append(settingToggle('unlimitedClues', text().unlimited), settingToggle('sound', text().sound)); const motion = document.createElement('select'); motion.setAttribute('aria-label', text().systemMotion); for (const [value, label] of [['system', text().systemMotion], ['reduced', text().reducedMotion]]) { const option = el('option', '', label); option.value = value; option.selected = settings.motion === value; motion.append(option); } motion.addEventListener('change', () => { settings = updateSetting(settings, 'motion', motion.value); saveSettings(storage, settings); applyTheme(); rebuildEffects(); }); form.append(settingRow(text().systemMotion, motion)); const contrast = document.createElement('select'); contrast.setAttribute('aria-label', text().standardContrast); for (const [value, label] of [['standard', text().standardContrast], ['high', text().contrast]]) { const option = el('option', '', label); option.value = value; option.selected = settings.contrast === value; contrast.append(option); } contrast.addEventListener('change', () => { settings = updateSetting(settings, 'contrast', contrast.value); saveSettings(storage, settings); applyTheme(); }); form.append(settingRow(text().standardContrast, contrast)); const language = button(text().language, () => { campaign.locale = campaign.locale === 'en' ? 'gu' : 'en'; updateCopy(); renderTargets(); save(); renderMenu('settings'); }, 'secondary'); language.classList.add('setting-action'); form.append(language); const coach = button(text().resetCoach, () => { settings = updateSetting(settings, 'coachDismissed', false); saveSettings(storage, settings); closePanel(); showCoach(); }, 'secondary'); coach.classList.add('setting-action'); form.append(coach); const reset = button(text().resetProgress, () => { if (campaign.migrationBlocked || endless.migrationBlocked || !window.confirm(text().resetProgressTitle + ' ' + text().resetProgressCopy)) return; const locale = campaign.locale; campaign = createCampaign(levels); campaign.locale = locale; endless = createContinuousRun(levels); restoreWarnings.journey = null; restoreWarnings.continuous = null; mode = 'journey'; level = levels[0]; ready = false; camera = { x: 0, y: 0, scale: 1 }; selected = null; closePanel(); loadLevel(level.id, false); }, 'secondary danger'); reset.classList.add('setting-action'); reset.disabled = Boolean(campaign.migrationBlocked || endless.migrationBlocked); form.append(reset); for (const blocked of [campaign.migrationBlocked, endless.migrationBlocked].filter(Boolean)) form.append(el('p', 'small-copy', migrationNotice(blocked, campaign.locale))); content.append(title, form); }
function renderHelpMenu(content) { const title = el('h3', '', text().howTo); title.id = 'menu-help-title'; content.append(title, el('p', 'help-copy', text().help), el('p', 'help-copy', text().inspect), button(text().continue, closePanel, 'primary')); }
function showLevels() { renderMenu('play', $('#levels-button')); }
function showCoach() { const coach = $('#coach'); if (!coach || settings.coachDismissed) return; coach.hidden = false; let step = 1; const steps = [...coach.querySelectorAll('[data-coach-step]')]; const next = coach.querySelector('[data-coach-next]'); const skip = coach.querySelector('[data-coach-skip]'); const finish = () => { settings = updateSetting(settings, 'coachDismissed', true); saveSettings(storage, settings); coach.hidden = true; }; const render = () => { steps.forEach((item) => { item.hidden = Number(item.dataset.coachStep) !== step; }); if (next) next.textContent = step === steps.length ? (campaign.locale === 'gu' ? 'સમજાયું' : 'Got it') : (campaign.locale === 'gu' ? 'આગળ' : 'Next'); }; if (next) next.onclick = () => { if (step >= steps.length) finish(); else { step += 1; render(); } }; if (skip) skip.onclick = finish; render(); }
function stats() { const row = el('div', 'stat-row'), values = [[text().time, formatElapsed(progress().elapsedMs)], [text().hints, hintBudget() - progress().hintsRemaining]]; if (mode === 'continuous') values.push([text().score, endless.score.toLocaleString()]); for (const [label, value] of values) { const cell = el('div'); cell.append(el('strong', '', value), el('span', '', label)); row.append(cell); } return row; }
function showPause() { openPanel(text().pause); body.append(el('p', '', mode === 'continuous' ? text().round + ' ' + endless.round + ' · ' + name(level) : name(level)), stats(), button(text().continue, closePanel, 'primary'), button(text().list, showLevels), button(text().language, () => { campaign.locale = campaign.locale === 'en' ? 'gu' : 'en'; updateCopy(); renderTargets(); save(); showPause(); })); if (mode === 'continuous') body.append(button(text().newRun, showNewRun, 'secondary danger')); else body.append(button(text().restart, showRestart, 'secondary danger')); body.append(el('p', 'help-copy', text().help), el('p', 'small-copy', progressCopy())); }
function showRestart() { openPanel(text().restartTitle); body.append(el('p', '', text().restartCopy), button(text().restart, () => { campaign.levels[level.id] = freshLevel(level); closePanel(); loadLevel(level.id, false); }, 'primary'), button(text().cancel, showPause)); }
function showNewRun() { openPanel(text().newRunTitle); body.append(el('p', '', text().newRunCopy), button(text().startNew, () => { save(); ready = false; endless = restartContinuousRun(endless, levels); closePanel(); level = levels.find((item) => item.id === endless.levelId); loadLevel(level.id, false); }, 'primary'), button(text().cancel, showPause)); }
function showComplete() { if (mode === 'continuous') { openPanel(text().roundComplete); body.append(el('div', 'complete-mark completion-entrance', '✓'), el('p', '', name(level) + ' · ' + progress().foundIds.length + ' / ' + activeTargets().length), stats()); const earned = el('div', 'round-points'); earned.append(el('span', '', text().points), el('strong', '', '+' + endless.lastRoundScore.toLocaleString())); body.append(earned, button(text().nextRound, () => { save(); ready = false; endless = advanceContinuousRound(endless, levels); closePanel(); level = levels.find((item) => item.id === endless.levelId); loadLevel(level.id, false); }, 'primary'), button(text().list, showLevels)); return; } const next = levels[levels.indexOf(level) + 1]; openPanel(next ? text().complete : text().allComplete); body.append(el('div', 'complete-mark completion-entrance', '✓'), el('p', '', name(level) + ' · ' + level.targets.length + ' / ' + level.targets.length), stats()); if (next) body.append(button(text().next, () => { closePanel(); loadLevel(next.id); }, 'primary')); else body.append(button(text().list, showLevels, 'primary')); body.append(button(text().replay, showRestart)); if (next) body.append(button(text().list, showLevels)); }
function discover(point) { if (!ready || panel.open || progress().complete) return; void effects.unlockAudio(); const remaining = sceneTargets().filter((target) => !progress().foundIds.includes(target.id)), id = hitTest(screenToScene(point, camera), remaining, camera.scale, 10); if (!id) { playMissFeedback(); toast(text().miss); return; } tick(); if (mode === 'continuous') endless = findContinuousTarget(endless, levels, id); else campaign = findCampaignTarget(campaign, levels, level.id, id); const target = levelTargets().find((item) => item.id === id), completed = progress().complete; if (completed) playCompleteFeedback(point, id); else playFindFeedback(point, id); $('#hint-region').hidden = true; renderTargets(); toast(name(target) + ' · ' + text().found); save(); if (completed) completionPresenter.schedule(); }
function installDistrictImage(image, district, direction, previousImage) { clearTimeout(transitionTimer); sceneImage.classList.remove('district-exit'); sceneIncoming.classList.remove('district-enter'); sceneIncoming.hidden = true; sceneIncoming.removeAttribute('src'); if (previousImage?.src) sceneImage.src = previousImage.src; const finish = () => { clearTimeout(transitionTimer); sceneImage.src = district.image; sceneImage.alt = `${name(level)} — ${name(district)}`; sceneImage.width = district.width; sceneImage.height = district.height; sceneImage.classList.remove('district-exit'); sceneIncoming.classList.remove('district-enter'); sceneIncoming.hidden = true; sceneIncoming.removeAttribute('src'); if (previousImage && previousImage !== image) previousImage.src = ''; }; if (!direction || !sceneImage.getAttribute('src')) { finish(); return; } scene.style.setProperty('--district-shift', direction < 0 ? '-8%' : '8%'); sceneIncoming.src = district.image; sceneIncoming.alt = ''; sceneIncoming.width = district.width; sceneIncoming.height = district.height; sceneIncoming.hidden = false; void sceneIncoming.offsetWidth; sceneIncoming.classList.add('district-enter'); sceneImage.classList.add('district-exit'); transitionTimer = setTimeout(finish, 260); }
function loadActiveDistrict({resume = true, direction = 0, focusTargetId = null, announce = false} = {}) {
  ready = false;
  // The persistent notice can change the viewport height. Measure after it is
  // visible, never against a placeholder or the pre-notice layout.
  renderMigrationNotice();
  size = rect();
  if (size.width <= 0 || size.height <= 0) return;
  restoreDistrictState({viewport: size, pixelRatio: window.devicePixelRatio || 1});
  const token = ++loadToken, district = activeDistrict(), previousImage = loadedImage;
  pointers.clear(); tap = null; pinch = null; clearTimeout(hintTimer);
  $('#hint-region').hidden = true; $('#loading').hidden = false;
  $('#retry').hidden = true; $('#loading .spinner').hidden = false;
  updateCopy(); renderDistrictNavigation(announce);
  $('#target-list').replaceChildren(); updateCounts();
  const image = new Image();
  const failed = () => {
    if (token !== loadToken) return;
    $('#loading-copy').textContent = text().error;
    $('#loading .spinner').hidden = true; $('#retry').hidden = false;
  };
  image.onload = () => {
    if (token !== loadToken) { image.src = ''; return; }
    if (image.naturalWidth !== district.width || image.naturalHeight !== district.height) { failed(); return; }
    loadedImage = image; loadedImageDistrictId = district.id;
    installDistrictImage(image, district, direction, previousImage);
    scene.style.width = district.width + 'px'; scene.style.height = district.height + 'px';
    size = rect(); cursor = { x: size.width / 2, y: size.height / 2 }; renderCursor();
    const stored = cameraForDistrict(districtState, district.id), pixelRatio = window.devicePixelRatio || 1;
    camera = resume && stored ? clampTransform(stored, size, district) : fitCamera(size, district, 'play', pixelRatio);
    const limit = scales();
    camera.scale = Math.max(limit.min, Math.min(limit.max, camera.scale));
    camera = clampTransform(camera, size, district);
    ready = true; lastTick = performance.now(); $('#loading').hidden = true;
    renderTargets(); renderDistrictNavigation(announce);
    const focusTarget = focusTargetId ? district.targets.find((target) => target.id === focusTargetId) : null;
    if (focusTarget) focusHintRegion(focusTarget);
    $('#gesture-note').classList.remove('fade'); clearTimeout(noteTimer);
    noteTimer = setTimeout(() => $('#gesture-note').classList.add('fade'), 4500);
    save();
  };
  image.onerror = failed; image.src = district.image;
}
function switchDistrict(id, direction, focusTargetId = null) { if (id === activeDistrict().id) { if (panel.open) closePanel(); const target = focusTargetId ? activeDistrict().targets.find((item) => item.id === focusTargetId) : null; if (target) focusHintRegion(target); return; } const from = level.districts.findIndex((district) => district.id === activeDistrict().id), to = level.districts.findIndex((district) => district.id === id); if (to < 0) return; save(); if (panel.open) closePanel(); ready = false; districtState = selectDistrict(districtState, level, id); setProgress({...progress(), districtState}); save(); loadActiveDistrict({resume: true, direction: direction ?? (to > from ? 1 : -1), focusTargetId, announce: true}); }
function stepActiveDistrict(delta) { const next = stepDistrict(districtState, level, delta); switchDistrict(next.activeDistrictId, delta); }
function loadLevel(id, resume = true) { if (mode === 'journey' && !campaign.unlockedLevelIds.includes(id)) return; completionPresenter.cancel(); save(); ready = false; if (mode === 'journey') campaign.currentLevelId = id; level = gameContext().level; if (!resume && mode === 'continuous') restoreWarnings.continuous = null; if (!resume) setProgress({...progress(), camera: null, districtState: createDistrictState(level)}); restoreDistrictState(); selected = null; lastFoundId = null; feedbackCleanup.clear(lastFoundOwner, 'last-found'); loadActiveDistrict({resume}); }

function localPoint(event) { const bounds = viewport.getBoundingClientRect(); return { x: event.clientX - bounds.left, y: event.clientY - bounds.top }; }
const distance = (a, b) => Math.hypot(a.x - b.x, a.y - b.y), midpoint = (a, b) => ({ x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 });
viewport.addEventListener('pointerdown', (event) => { if (!ready || panel.open || event.target.closest('button') || event.button > 0) return; event.preventDefault(); const point = localPoint(event); viewport.setPointerCapture(event.pointerId); pointers.set(event.pointerId, point); $('#gesture-note').classList.add('fade'); viewport.classList.add('dragging'); if (pointers.size === 1) tap = { id: event.pointerId, ...point, moved: false, multi: false, fitScale: Math.abs(camera.scale - scales().min) < 1e-6, start: performance.now() }; else { if (tap) { tap.multi = true; tap.fitScale = false; } const [a, b] = [...pointers.values()]; pinch = { distance: distance(a, b), midpoint: midpoint(a, b), camera: { ...camera } }; } });
viewport.addEventListener('pointermove', (event) => { if (!pointers.has(event.pointerId)) return; const previous = pointers.get(event.pointerId), point = localPoint(event), district = activeDistrict(); pointers.set(event.pointerId, point); if (tap && distance(tap, point) > 9) tap.moved = true; if (pointers.size === 1) camera = clampTransform({ ...camera, x: camera.x + point.x - previous.x, y: camera.y + point.y - previous.y }, size, district); else if (pinch && pinch.distance > 0) { const [a, b] = [...pointers.values()], middle = midpoint(a, b), limits = scales(), scale = Math.min(limits.max, Math.max(limits.min, pinch.camera.scale * distance(a, b) / pinch.distance)); const next = zoomAroundPoint(pinch.camera, scale, pinch.midpoint); camera = clampTransform({ ...next, x: next.x + middle.x - pinch.midpoint.x, y: next.y + middle.y - pinch.midpoint.y }, size, district); if (tap) tap.fitScale = false; } if (tap && Math.abs(camera.scale - scales().min) >= 1e-6) tap.fitScale = false; renderCamera(); });
function release(event) { if (!pointers.has(event.pointerId)) return; const point = localPoint(event), gesture = tap; if (gesture && distance(gesture, point) > 9) gesture.moved = true; const single = gesture?.id === event.pointerId && pointers.size === 1, valid = single && isValidTap(gesture, event.type, performance.now()), swipe = single && event.type === 'pointerup' && !gesture.multi ? districtSwipeDirection(gesture, point, gesture.fitScale && Math.abs(camera.scale - scales().min) < 1e-6) : 0; pointers.delete(event.pointerId); if (viewport.hasPointerCapture(event.pointerId)) viewport.releasePointerCapture(event.pointerId); if (pointers.size === 0) { tap = null; pinch = null; viewport.classList.remove('dragging'); } else { tap = null; pinch = null; } if (swipe) { stepActiveDistrict(swipe); return; } if (valid && point.x >= 0 && point.y >= 0 && point.x <= size.width && point.y <= size.height) discover(point); scheduleSave(); }
viewport.addEventListener('pointerup', release); viewport.addEventListener('pointercancel', release);
viewport.addEventListener('wheel', (event) => { if (event.target.closest('button')) return; event.preventDefault(); zoom(Math.exp(-event.deltaY * .0015), localPoint(event)); }, { passive: false }); viewport.addEventListener('contextmenu', (event) => event.preventDefault());
viewport.addEventListener('keydown', (event) => { if (event.target !== viewport || !ready) return; const amount = event.shiftKey ? 150 : 60; if (['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown'].includes(event.key)) { event.preventDefault(); if (!event.shiftKey) { cursor = moveSearchCursor(cursor, event.key, size); renderCursor(); return; } camera.x += event.key === 'ArrowLeft' ? amount : event.key === 'ArrowRight' ? -amount : 0; camera.y += event.key === 'ArrowUp' ? amount : event.key === 'ArrowDown' ? -amount : 0; camera = clampTransform(camera, size, activeDistrict()); renderCamera(); scheduleSave(); } else if (['+', '=', '-', 'Enter', ' ', 'Home'].includes(event.key)) { event.preventDefault(); if (event.key === 'Home') overview(); else if (event.key === 'Enter' || event.key === ' ') discover(cursor); else zoom(event.key === '-' ? 1 / 1.35 : 1.35); } });
$('#zoom-in').onclick = () => zoom(1.35); $('#zoom-out').onclick = () => zoom(1 / 1.35); $('#overview').onclick = overview; $('#levels-button').onclick = showLevels; $('#pause-button').onclick = showPause; $('#close-panel').onclick = closePanel; $('#retry').onclick = () => loadActiveDistrict({resume: true}); $('#previous-district').onclick = () => stepActiveDistrict(-1); $('#next-district').onclick = () => stepActiveDistrict(1); for (const node of document.querySelectorAll('.district-button')) node.onclick = () => switchDistrict(node.dataset.districtId);
$('#hint-button').onclick = () => { const target = activeTargets().find((item) => item.id === selected && !progress().foundIds.includes(item.id)) || activeTargets().find((item) => !progress().foundIds.includes(item.id)); if (target) showTarget(target); };
constrainedTargetMedia?.addEventListener?.('change', () => { if (ready) renderTargets(); });
reducedMotionMedia?.addEventListener?.('change', () => rebuildEffects());
panel.addEventListener('close', () => { const opener = menuOpener; menuState = closeMenu(menuState); menuOpener = null; panel.classList.remove('menu-panel'); lastTick = performance.now(); save(); completionPresenter.panelClosed(); opener?.focus?.(); });
new ResizeObserver(() => { const next = rect(); if (!ready) { const waitingForViewport = size.width <= 0 || size.height <= 0; size = next; if (waitingForViewport && next.width > 0 && next.height > 0) loadActiveDistrict(); return; } if (next.width === size.width && next.height === size.height) return; const district = activeDistrict(); camera = resizeCamera(camera, size, next, district, window.devicePixelRatio || 1); size = next; cursor = { x: size.width / 2, y: size.height / 2 }; renderCursor(); const limits = scales(); camera.scale = Math.max(limits.min, Math.min(limits.max, camera.scale)); camera = clampTransform(camera, size, district); renderCamera(); scheduleSave(); }).observe(viewport);
document.addEventListener('visibilitychange', () => { if (document.hidden) { tick(); save(); } lastTick = performance.now(); }); window.addEventListener('pagehide', () => { void effectsLifecycle.pagehide(); }); window.addEventListener('pageshow', () => { lastTick = performance.now(); effectsLifecycle.pageshow(); });
setInterval(tick, 500); setInterval(() => { if (ready && !document.hidden) save(); }, 10000); applyTheme(); loadLevel(level.id); setTimeout(showCoach, 0);
